network info is probably only available when connected
koreader/koreader pull request #10062
Opened 2023-01-31 20:50 UTC by yparitcher

Follow up to #10059.

Many of the devices use the same function to back both `iswifion()` and `isConnected()`. I think they represent different things, 1. is the radio on 2. are we connected to a network.

I fixed this for kindle, but asking for the other devices,

- [ ] Android: @pazos I am not sure exactly what the jni getNetworkInfo is looking for.
- [ ] Cervantes: Uses the same check as Kindle, so if nobody objects, I will split it properly also. (`/sys/class/net/*/carrier`)
- [x] Kobo: `iswifion`: look for wifi module. `isConnected`: gateway ping
- [ ] Pocketbook: @rjd22  Both: `band(inkview.QueryNetwork(), C.NET_CONNECTED) ~= 0`
- [ ] Remarkable: Both: gateway ping. `isWifiOn` is aliased to `isConnected`
- [x] Sdl: `isWifiOn` not supported. `isConnected`: gateway ping
- [x] Sony-prstux: `iswifion`: `os.execute("wmiconfig -i wlan0 --wlan query | grep -q enabled")`. `isConnected`: gateway ping

2023-01-31 21:15 UTC, Frenzie commented
>  Android: @pazos I am not sure exactly what the jni getNetworkInfo is looking for.

It returns ssid, ip and gateway.

2023-01-31 21:29 UTC, pazos commented
Returns https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt#L122-L187

a couple of values: true or false & integer representing connection type, as in https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L464-L471

Makes sense to treat the first value as `isConnected` instead of `isWifiOn` 

What @Frenzie said was the previous behaviour, deprecated around 2019/20, IIRC because we cannot  handle wifi ourselves on newer android versions and the check wouldn't cover other kind of network connectivity

2023-01-31 21:33 UTC, NiLuJe commented
IIRC, that check is slightly off on purpose to avoid a costlier call in a common menu generation codepath.

(i.e., isWifiOn can usually be fast, isConnected is generally slower and blocking).

2023-01-31 21:37 UTC, Frenzie commented
> What @Frenzie said was the previous behaviour, deprecated around 2019/20

Whoops, I forgot or missed that it changed then. 

> (i.e., isWifiOn can usually be fast, isConnected is generally slower and blocking).

That depends a bit on the system. On Android it's updated once a second or whatever so you immediately get some cached value.

2023-01-31 23:03 UTC, yparitcher commented
So android only implements `isConnected` and we use it as `isWifiOn`.
Doew android support finding out if the radio/wifi is on, even if not connected?

2023-02-01 04:53 UTC, yparitcher commented
now `NetworkMgr:isConnected()` is defined as a gateway ping. any device that has a different way to check connectivity, redefines it in the device specific `initNetworkManager`.
Any device whose `isWifiOn` is really checking for connection has the definitions updated to `isConnected` being canonical and `isWifiOn` aliased to it.

I think this is a better defined & more future proof way to go about this.

2023-02-01 04:54 UTC, yparitcher commented
If any device has a beeter way for either `isWifiOn` or `isConnected` they can easily define it now.

2023-02-01 08:52 UTC, Frenzie commented
> a better way

Or because it can't do it. Better isn't implied anywhere. ;-)

2023-02-01 17:33 UTC, yparitcher commented
If did for `iswifion` i made it more explicit for `isConnected`

2023-02-05 18:59 UTC, NiLuJe commented
I wouldn't mind moving the Kobo isConnected to use the sysfs carrier check, too, because that gateway ping is annoying as all hell (and is very much the reason I didn't want to use isConnected in menu instantiation code).

2023-02-05 19:13 UTC, yparitcher commented
Do all kobos have a consistent carrier file? Wlan0 or eth0?

2023-02-05 19:26 UTC, NiLuJe commented
If it works on Cervantes, it should work here too (same OEM, meaning same old-as-hell kernels).

The only thing you need to be careful about is picking the right interface; the startup scripts sets the `INTERFACE` env var for that:

https://github.com/koreader/koreader/blob/3881899338fbd05d1acd3e08d0dcf012f748bab4/frontend/device/kobo/device.lua#L857-L860

2023-02-05 20:00 UTC, Frenzie commented
Is that the same state as isConnected or actually a third state?

2023-02-05 20:17 UTC, NiLuJe commented
It technically means "phy link is up", which, mmmkay, is good enough, I guess? ;o). (I really, really, really *hate* that gw ping).

(I don't recall when it flips re: association, where wifi is concerned, though...).

2023-02-05 20:24 UTC, Frenzie commented
> It technically means "phy link is up", which, mmmkay, is good enough, I guess? ;o).

I don't think that's quite true for wifi as opposed to ethernet?

> (I really, really, really hate that gw ping).

Sounds like you're trying to use it for something it's not intended for. ;-) (E.g., it's definitely not intended for the menu!)

2023-02-05 21:03 UTC, yparitcher commented
Migrated kobo to use the carrier file.
The only devices still using the gw ping are: remarkable, sdl (!emulator) & sony

2023-02-05 21:09 UTC, yparitcher commented
Also kindle was opening the file "re" cloxec, i assumed that we should stick to "rb" to cover kobo/cervantes.

2023-02-05 21:19 UTC, yparitcher commented
Remakable implements getnetworkinterfacename so i should be able to have it use the carrier file, but i need testers.

Also auto wifi off is only enabled if haswifimanager, it seems to only rely on getnetworkinterfacename & sysfs, so can i enable it on kindle etc (embedded linux with root)?

2023-02-05 21:46 UTC, NiLuJe commented
> Also kindle was opening the file "re" cloxec, i assumed that we should stick to "rb" to cover kobo/cervantes.

No, CLOEXEC might be critical, depending on timing, as wpa_supplicant might inherit the fd otherwise, and it then breaks USBMS.

There are no Kobo or Cervantes devices old enough to *not* support CLOEXEC, so there's no compatibility issue.

2023-02-05 21:47 UTC, NiLuJe commented
> Also auto wifi off is only enabled if haswifimanager, it seems to only rely on getnetworkinterfacename & sysfs, so can i enable it on kindle etc (embedded linux with root)?

You might have issues with the threshold on Kindle, given the chatty nature of the stock OS (this, and lack of testing, is probably why I kept it restricted to what I could test on).

2023-02-05 21:49 UTC, NiLuJe commented
> Sounds like you're trying to use it for something it's not intended for. ;-) (E.g., it's definitely not intended for the menu!)

Which is exactly why I objected to that chunk in https://github.com/koreader/koreader/pull/10062#issuecomment-1411097679 ;).

2023-02-05 22:07 UTC, yparitcher commented
> > Also kindle was opening the file "re" cloxec, i assumed that we should stick to "rb" to cover kobo/cervantes.
> 
> No, CLOEXEC might be critical, depending on timing, as wpa_supplicant might inherit the fd otherwise, and it then breaks USBMS.
> 
> There are no Kobo or Cervantes devices old enough to *not* support CLOEXEC, so there's no compatibility issue.

Cervantes, was using "rb" thats why i thought so. Will change to "re"

2023-02-05 22:08 UTC, yparitcher commented
> > Sounds like you're trying to use it for something it's not intended for. ;-) (E.g., it's definitely not intended for the menu!)
> 
> Which is exactly why I objected to that chunk in https://github.com/koreader/koreader/pull/10062#issuecomment-1411097679 ;).

I didn't realize what you were referring to there. But at least we now can have just sdl and sony using it

2023-02-05 22:10 UTC, yparitcher commented
> > Also auto wifi off is only enabled if haswifimanager, it seems to only rely on getnetworkinterfacename & sysfs, so can i enable it on kindle etc (embedded linux with root)?
> 
> You might have issues with the network activity threshold on Kindle, given the chatty nature of the stock OS (this, and lack of testing, is probably why I kept it restricted to what I could test on).

Will test on my device. (My iptables config limits connections to the local network (no need for Amazon's snooping), so the is might be less of an issue)

2023-02-06 13:58 UTC, yparitcher commented
Current status:

- [ ] Android: @pazos is there a simple way to get the wifi radio state (on/off)? If not we can leave it as is.
- [x] Cervantes: carrier check
- [x] Kindle: carrier check
- [x] Kobo: carrier check
- [x] Pocketbook: @rjd22  Both: `band(inkview.QueryNetwork(), C.NET_CONNECTED) ~= 0`
- [x] Remarkable: carrier check (needs testers to confirm)
- [ ] Sdl: the whole networkmanager is not supported (besides emulator) so i can get rid of isconnected once it is not being used by anything else.
- [ ] Sony-prstux: has wifimanager. Can i change it to using a carrier check? Would it support CLOEXEC? @NiLuJe 

Once i migrate sony-prstux, i will get rid of the gw check.

2023-02-06 14:20 UTC, pazos commented
> Android: @pazos is there a simple way to get the wifi radio state (on/off)? If not we can leave it as is.

Sorry, not sure if I follow.

The way to check network connectivity **and** wifi is possible but other kind of connectivity is also possible and valid, so please leave it as is or we're going to break cell, ethernet and bluetooth network capabilities if we're going to only take wifi as a valid answer

2023-02-06 14:55 UTC, yparitcher commented
Ok i get it now, as a tradeoff for having multiple valid connection types it does not make sense to check if the radio is on or off. Thanks for the clarification.

2023-02-06 21:53 UTC, NiLuJe commented
> * Sony-prstux: has wifimanager. Can i change it to using a carrier check? Would it support CLOEXEC?

IIRC, it's an Android kernel, so I'm going to assume "yes, it'll support CLOEXEC". That platform is essentially DOA as no-one can replicate it, so you can't really do anything wrong there ;p.

2023-02-07 02:57 UTC, yparitcher commented
It seems that sdl needs some sort of is connected for OPDS & friends :(
That it worked till now is lucky, as sdl does not have a `isWifiOn` so anything checking for both fails, only `runWhenConnected` worked as it only checks `isConnected`.

Should i leave it with the gateway ping, or should we try some other way?

2023-02-07 04:34 UTC, NiLuJe commented
> Should i leave it with the gateway ping, or should we try some other way?

I'd probably paper over it by enforcing `isWifiOn` to `true` for now?

Any actual solution for a theoretical use on a device that isn't the emu would require more specific trickery that we can't quite generalize, I think?

2023-02-07 06:29 UTC, Frenzie commented
> Should i leave it with the gateway ping, or should we try some other way?

For desktop it should just return true, but what are you implying about changing behavior here on the actual platforms it's for exactly?

2023-02-07 20:24 UTC, Frenzie approved these changes
lgtm (but I didn't check each and every device in detail, mainly just android/generic/kobo/sdl)

2023-02-07 20:46 UTC, yparitcher commented
Ready on my end, tested on kindle and sdl

If you want to test on kobo go ahead, otherwise i will merge tonight.

Auto off for kindle is coming on a separate PR

2023-02-08 00:22 UTC, NiLuJe requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10062)* status: all files reviewed, 1 unresolved discussion (waiting on @pazos, @poire-z, and @yparitcher)

___
*[`frontend/device/sdl/device.lua` line 377 at r1](https://reviewable.io/reviews/koreader/koreader/10062#-NNiO8J48zVgEVUZgQyA:-NNiO8J48zVgEVUZgQyB:b-y9o8wk) ([raw file](https://github.com/koreader/koreader/blob/90e9c34e91acc3bd726b1e721d99b418c804ab26/frontend/device/sdl/device.lua#L377)):*
> ```Lua
>             std_out = io.popen([[ip r | grep default | tail -n 1 | cut -d ' ' -f 3]], "r")
>         else
>             std_out = io.popen([[/sbin/route -n | awk '$4 == "UG" {print $2}' | tail -n 1]], "r")
> ```

I'd get rid of the absolute path and leave it to PATH resolution.

(e.g., it happens to live in `/bin` on my system)


<!-- Sent from Reviewable.io -->

2023-02-08 04:46 UTC, NiLuJe approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10062)* status: all files reviewed, 1 unresolved discussion (waiting on @pazos, @poire-z, and @yparitcher)



<!-- Sent from Reviewable.io -->

2023-02-08 05:06 UTC, merged