Readerzooming: fix use of default settings
koreader/koreader pull request #10205
Opened 2023-03-14 12:12 UTC by hius07

(1) Fix default direction. Closes https://github.com/koreader/koreader/issues/10201. Fixes https://github.com/koreader/koreader/issues/9321.
(2) Fix default overlap (unreported bug).
(3) Do not write unused settings to doc_settings.

2023-03-14 17:23 UTC, NiLuJe approved these changes
Besides that small comment nit, that cerainly looks much more sensible, thanks for looking into this!

2023-03-14 17:28 UTC, hius07 commented on frontend/apps/reader/modules/readerzooming.lua
> +    local settings = { -- untie the tables
I meant that we cannot have just

`local settings = self.zoom_direction_settings[config.zoom_direction]`

2023-03-14 17:31 UTC, hius07 commented on frontend/apps/reader/modules/readerzooming.lua
> +    local settings = { -- untie the tables
Because `settings` table is modified further and this will damage `self`.

2023-03-14 17:41 UTC, NiLuJe requested changes

2023-03-14 17:41 UTC, NiLuJe commented on frontend/apps/reader/modules/readerzooming.lua
> +    local settings = { -- untie the tables
I get that; I'd just explicitly say that we *need* to work on a local copy, paired with the `-- const` tag in the class member that was lost here to tie it all together ;).

2023-03-14 17:42 UTC, NiLuJe commented
(Sorry, clicked that damn review button again >_<").

2023-03-15 01:17 UTC, mergen3107 commented
Thank you very much @hius07!
Can’t wait to test this out

2023-03-15 15:27 UTC, NiLuJe approved these changes

2023-03-23 08:00 UTC, poire-z approved these changes
Not familiar with the code, but ok, go ahead merging.

2023-03-23 08:05 UTC, merged