Write highlights into PDF: revisited
koreader/koreader pull request #12509
Opened 2024-09-12 15:12 UTC by hius07

![1](https://github.com/user-attachments/assets/89eecfcb-39d1-4537-98c8-066533d0324e)

![2](https://github.com/user-attachments/assets/6482091d-9bbf-42f8-a730-12a8e49f31fb)

![3](https://github.com/user-attachments/assets/73edf51f-e7d8-4c66-a385-c6a7db7a01ec)

![4](https://github.com/user-attachments/assets/4d687065-226a-4cdb-be50-57368cdc8c2f)

Closes https://github.com/koreader/koreader/issues/12500.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12509)

2024-09-12 15:26 UTC, hius07 commented
> Lowecase on/off is normally only for the bottom menu btw.

I cannot find any "On" or "Off" uppercased.
Gesture manager shows "on" and "off".

2024-09-12 15:54 UTC, hius07 commented
![5](https://github.com/user-attachments/assets/14092e75-0eac-4d3a-abe5-0b8575192d26)

2024-09-12 16:52 UTC, hius07 commented
CircleCI warnings:

`WARN  could not load liblipclua: module 'liblipclua' not found:`

`ERROR Failed to initialize terminal plugin: plugins/terminal.koplugin/main.lua:108: wrong number of arguments to 'insert'`

`WARN  Error when loading plugins/coverbrowser.koplugin/main.lua common/lua-ljsqlite3/init.lua:109: ';' expected near '='`

```
ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02bbea7f0 still has count 1 (id ./data/tessdata/eng.traineddatapunc-dawg)
ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02bbea860 still has count 1 (id ./data/tessdata/eng.traineddataword-dawg)
ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02bbea910 still has count 1 (id ./data/tessdata/eng.traineddatanumber-dawg)
ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02c1a4650 still has count 1 (id ./data/tessdata/eng.traineddatabigram-dawg)
ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02c1a4c90 still has count 1 (id ./data/tessdata/eng.traineddatafreq-dawg)
make: unlink: base/thirdparty/kpvcrlib/crengine/cr3gui/data/tessdata: Is a directory
```

2024-09-12 17:09 UTC, hius07 commented
Interesting feature would be scanning a pdf file for existing embedded highlights and creating our corresponding annotations. Dunno if MuPDF can do it.
@benoit-pierre ?

2024-09-12 17:15 UTC, benoit-pierre commented
> CircleCI warnings:
> 
> `WARN could not load liblipclua: module 'liblipclua' not found:`

Expected.

> `ERROR Failed to initialize terminal plugin: plugins/terminal.koplugin/main.lua:108: wrong number of arguments to 'insert'`

Not sure about that one (I've just nuked the plugin locally after getting tired of it preventing KOReader' startup on Android).
 
> `WARN Error when loading plugins/coverbrowser.koplugin/main.lua common/lua-ljsqlite3/init.lua:109: ';' expected near '='`

Expected (lack of proper isolation when running tests).

> ```
> ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02bbea7f0 still has count 1 (id ./data/tessdata/eng.traineddatapunc-dawg)
> ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02bbea860 still has count 1 (id ./data/tessdata/eng.traineddataword-dawg)
> ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02bbea910 still has count 1 (id ./data/tessdata/eng.traineddatanumber-dawg)
> ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02c1a4650 still has count 1 (id ./data/tessdata/eng.traineddatabigram-dawg)
> ObjectCache(0x7f1a4fd36200)::~ObjectCache(): WARNING! LEAK! object 0x55f02c1a4c90 still has count 1 (id ./data/tessdata/eng.traineddatafreq-dawg)
> make: unlink: base/thirdparty/kpvcrlib/crengine/cr3gui/data/tessdata: Is a directory
> ```

I investigated that one, and there did not seem to be a real leak, might look into it again after #12497.

2024-09-12 17:15 UTC, NiLuJe commented
> WARN could not load liblipclua: module 'liblipclua' not found:

Normal, kindle codepath.

> ERROR Failed to initialize terminal plugin: plugins/terminal.koplugin/main.lua:108: wrong number of arguments to 'insert'

Might actually be a bug, but I don't recall if there are still terminal PRs in flight about that ;).

> WARN Error when loading plugins/coverbrowser.koplugin/main.lua common/lua-ljsqlite3/init.lua:109: ';' expected near '='

Also expected, ye olde' busted.

2024-09-12 17:15 UTC, NiLuJe commented
Welp, I was too slow ;p.

2024-09-12 17:20 UTC, benoit-pierre commented
> Interesting feature would be scanning a pdf file for existing embedded highlights and creating our corresponding annotations. Dunno if MuPDF can do it. @benoit-pierre ?

Using those to iterate over a pages annotations (like we already do in `getMarkupAnnotation`):
```c
/*
	Returns a borrowed reference to the first annotation on
	a page, or NULL if none.

	The caller should fz_keep this if it intends to hold the
	pointer. Unless it fz_keeps it, it must not fz_drop it.
*/
pdf_annot *pdf_first_annot(fz_context *ctx, pdf_page *page);

/*
	Returns a borrowed reference to the next annotation
	on a page, or NULL if none.

	The caller should fz_keep this if it intends to hold the
	pointer. Unless it fz_keeps it, it must not fz_drop it.
*/
pdf_annot *pdf_next_annot(fz_context *ctx, pdf_annot *annot);
```

2024-09-12 17:34 UTC, Frenzie commented
> I've just nuked the plugin locally after getting tired of it preventing KOReader' startup on Android

You can simply disable it btw. (Unless that's what you meant by "nuke")

2024-09-12 17:34 UTC, hius07 commented
> Using those to iterate over a page's annotations (like we already do in `getMarkupAnnotation`):

Thanks, looks like I cannot do it in frontend, new methods in mupdf.lua are required. Postponing so far.

2024-09-12 17:37 UTC, benoit-pierre commented
> > I've just nuked the plugin locally after getting tired of it preventing KOReader' startup on Android
> 
> You can simply disable it btw.

That does not help on that first startup, which is when the shell detection fails.

> (Unless that's what you meant by "nuke")

Nope. :P

2024-09-12 17:38 UTC, Frenzie commented
> Might actually be a bug, but I don't recall if there are still terminal PRs in flight about that ;).

#12384 remains in a bit of limbo atm.

2024-09-12 17:40 UTC, Frenzie commented
> That does not help on that first startup, which is when the shell detection fails.

Fair enough, but while it doesn't seem to be working quite right for me atm (and I think it used to?), it doesn't have any such effects.

2024-09-13 11:09 UTC, NiLuJe requested changes
Looks good, just a few questions basically ;).

> Reviewed 8 of 10 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12509#-:-O6f3h6dCogQNS7P_jDr:b2w0tne)* status: all files reviewed, 9 unresolved discussions (waiting on @hius07)

___
*[`frontend/apps/filemanager/filemanagermenu.lua` line 948 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6ez1No5qNWr8FVdI-E:-O6ez1No5qNWr8FVdI-F:bcvwqy5) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/filemanager/filemanagermenu.lua#L948)):*
> ```Lua
>     end
> 
>     UIManager:close(self.menu_container)
> ```

What's the rationale for moving this after the `ConfirmBox`?
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 560 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f11liC9DbidNnE3TV:-O6f11liC9DbidNnE3TW:b-fevcpr) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readerhighlight.lua#L560)):*
> ```Lua
>             text_func = function()
>                 local text = self.highlight_write_into_pdf and _("on") or _("off")
>                 if (not self.highlight_write_into_pdf) == (not G_reader_settings:isTrue("highlight_write_into_pdf")) then
> ```

Is there a quirk I'm missing that wouldn't allow writing this as

`if self.highlight_write_into_pdf == G_reader_settings:isTrue("highlight_write_into_pdf" then`

instead?
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 661 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f1lJ_CqMUfbuCUuPq:-O6f1lJ_CqMUfbuCUuPr:b-bdj2cq) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readerhighlight.lua#L661)):*
> ```Lua
>                     callback = function()
>                         UIManager:show(ConfirmBox:new{
>                             text = _("Are you sure you want to delete all highlights from pdf file?"),
> ```

We *might* want to explain that this currently only applies to *KOReader* highlights.
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 2426 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f2D123GGZithfBCyc:-O6f2D123GGZithfBCyd:b-29quf1) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readerhighlight.lua#L2426)):*
> ```Lua
>                 self.highlight_write_into_pdf = config:isTrue("highlight_write_into_pdf") -- true or false
>             else
>                 self.highlight_write_into_pdf = G_reader_settings:readSetting("highlight_write_into_pdf") -- true or nil
> ```

Ah. That could be the quirk I was looking for above ;).

Maybe use `G_reader_settings:readSetting("highlight_write_into_pdf") or false` to avoid the inconsistency?
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 2452 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f2UNNEbmhEvh2Ezq2:-O6f2UNNEbmhEvh2Ezq3:bbzypr8) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readerhighlight.lua#L2452)):*
> ```Lua
>     self.ui.doc_settings:saveSetting("highlight_drawer", self.view.highlight.saved_drawer)
>     self.ui.doc_settings:saveSetting("highlight_color", self.view.highlight.saved_color)
>     self.ui.doc_settings:saveSetting("highlight_write_into_pdf", self.highlight_write_into_pdf)
> ```

Which would imply we always write this in doc_settings (which I'm fine with, mind you, just mentioning that in passing ;)).
___
*[`frontend/apps/reader/modules/readermenu.lua` line 378 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f2gjB4NxwiuRenstL:-O6f2gjB4NxwiuRenstM:bzag3q0) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readermenu.lua#L378)):*
> ```Lua
>     end
> 
>     self:onTapCloseMenu()
> ```

Same question as in FMMenu ;).
___
*[`frontend/apps/reader/modules/readermenu.lua` line 409 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f34Wy8K70zBvhp7MT:-O6f34Wy8K70zBvhp7MU:b-6o6tzb) ([raw file](https://github.com/koreader/koreader/blob/57ceaf3f07eb54ca0ee14c2a5a61dd108d062e97/frontend/apps/reader/modules/readermenu.lua#L409)):*
> ```Lua
>     if FileManager.instance then
>         FileManager.instance:onClose()
>     end
> ```

Closing FM *before* the nextTick was *really really* important, IIRC ;).



_Code quote:_
```Lua
    local FileManager = require("apps/filemanager/filemanager")
    if FileManager.instance then
        FileManager.instance:onClose()
    end
```
___
*[`frontend/ui/data/onetime_migration.lua` line 711 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f3N7i903ayOzuIfME:-O6f3N7i903ayOzuIfMF:b-62zz4l) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/ui/data/onetime_migration.lua#L711)):*
> ```Lua
> end
> 
> -- 20240912, Write highlights to PDF: revisited
> ```

Missing the PR link in the comment ;).
___
*[`frontend/ui/elements/common_settings_menu_table.lua` line 569 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f3Ysz5JuuRGkpNSJ2:-O6f3Ysz5JuuRGkpNSJ3:bybppa2) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/ui/elements/common_settings_menu_table.lua#L569)):*
> ```Lua
> local metadata_folder_help_text = table.concat(metadata_folder_help_table, "\n")
> 
> local hash_filemod_warn = T(_("%1 requires calculating partial file hashes of documents which may slow down file browser navigation. Any file modifications (such as embedding annotations into PDF files or downloading from calibre) may change the partial hash, thereby losing track of any highlights, bookmarks, and progress data. Embedding PDF annotations can be set at menu Typeset - Highlights - Write highlights into PDF."), metadata_folder_str.hash)
> ```

nit: The fancy arrows → were nicer ;).



_Code quote:_
```Lua
local hash_filemod_warn = T(_("%1 requires calculating partial file hashes of documents which may slow down file browser navigation. Any file modifications (such as embedding annotations into PDF files or downloading from calibre) may change the partial hash, thereby losing track of any highlights, bookmarks, and progress data. Embedding PDF annotations can be set at menu Typeset - Highl
```


<!-- Sent from Reviewable.io -->

2024-09-13 11:48 UTC, hius07 reviewed
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12509)* status: 7 of 10 files reviewed, 8 unresolved discussions (waiting on @NiLuJe)

___
*[`frontend/apps/filemanager/filemanagermenu.lua` line 948 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6ez1No5qNWr8FVdI-E:-O6f7ilK5hFWicArIPxq:b-q6scja) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/filemanager/filemanagermenu.lua#L948)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

What's the rationale for moving this after the `ConfirmBox`?
</blockquote></details>

Old code: the menu widget goes closed, if a user decides to "Restart anyway", `UImanager:close` is called once more on closed widget.
My code: ConfirmBox appears, the menu is kept open. If a user decides to "exit", he has an opened menu for that. If a user decides to "Restart anyway", the menu closes only once.
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 661 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f1lJ_CqMUfbuCUuPq:-O6f9exi-h9rh6T7uwof:b-896fix) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readerhighlight.lua#L661)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

We *might* want to explain that this currently only applies to *KOReader* highlights.
</blockquote></details>

Done.
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 2426 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f2D123GGZithfBCyc:-O6f9h4lDXWYMwQKhcNO:b-67d0i0) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readerhighlight.lua#L2426)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

Ah. That could be the quirk I was looking for above ;).

Maybe use `G_reader_settings:readSetting("highlight_write_into_pdf") or false` to avoid the inconsistency?
</blockquote></details>

On clean install, G_ setting is absent (nil), and doc_ setting will be absent until a user changes it to "off", then it becomes false.
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 2452 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f2UNNEbmhEvh2Ezq2:-O6fABJj01SE6Ui6Gnfd:b1dyscn) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/apps/reader/modules/readerhighlight.lua#L2452)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

Which would imply we always write this in doc_settings (which I'm fine with, mind you, just mentioning that in passing ;)).
</blockquote></details>

The doc_ setting appears in sdr only when a user changes it (choosing "On" or "Off" that is the per document setting). Until then it remains nil.
___
*[`frontend/apps/reader/modules/readermenu.lua` line 409 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f34Wy8K70zBvhp7MT:-O6fAPRv-hXeYcS5G-zW:b1zu51g) ([raw file](https://github.com/koreader/koreader/blob/57ceaf3f07eb54ca0ee14c2a5a61dd108d062e97/frontend/apps/reader/modules/readermenu.lua#L409)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

Closing FM *before* the nextTick was *really really* important, IIRC ;).
</blockquote></details>

We should not have FileManager.instance when we have ReaderUi.instance, right?
If it appears somehow, we should fix the bug at the source.
___
*[`frontend/ui/data/onetime_migration.lua` line 711 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f3N7i903ayOzuIfME:-O6fAvjD3OkOzIA-PYIS:bb6un1j) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/ui/data/onetime_migration.lua#L711)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

Missing the PR link in the comment ;).
</blockquote></details>

Done
___
*[`frontend/ui/elements/common_settings_menu_table.lua` line 569 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f3Ysz5JuuRGkpNSJ2:-O6fBtzzCqoEPF61NsmZ:bb6un1j) ([raw file](https://github.com/koreader/koreader/blob/03903f027847b66bb0aa4f2f6d6dfec2af178f3e/frontend/ui/elements/common_settings_menu_table.lua#L569)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

nit: The fancy arrows → were nicer ;).
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-13 12:06 UTC, NiLuJe approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12509)* status: all files reviewed, 1 unresolved discussion (waiting on @hius07)

___
*[`frontend/apps/reader/modules/readermenu.lua` line 409 at r4](https://reviewable.io/reviews/koreader/koreader/12509#-O6f34Wy8K70zBvhp7MT:-O6fGYcjBmvnr2Mgu-yC:bg22mj4) ([raw file](https://github.com/koreader/koreader/blob/57ceaf3f07eb54ca0ee14c2a5a61dd108d062e97/frontend/apps/reader/modules/readermenu.lua#L409)):*
<details><summary><i>Previously, hius07 wrote…</i></summary><blockquote>

We should not have FileManager.instance when we have ReaderUi.instance, right?
If it appears somehow, we should fix the bug at the source.
</blockquote></details>

Oops, I somehow thought this was a FM menu, not a Reader one, my bad ;).

FWIW, this has been in there since the inception of the `exitOrRestart` methods waaaay back in https://github.com/koreader/koreader/pull/2772 ;).


<!-- Sent from Reviewable.io -->

2024-09-13 19:01 UTC, poire-z approved these changes
Not familiar with all that, looks ok, trusting you.

2024-09-14 12:21 UTC, merged