ReaderFooter: update FL on toggle
koreader/koreader pull request #6664
Opened 2020-09-17 03:50 UTC by yparitcher

isFrontlightOnHW() was returning a value from front not from hardware before front is updated, therefore _decideFrontlightState() would have the old state.

The FrontlightStateChanged event used by ReaderFooter was called by _setIntensity before powerd.is_fl_on was toggled

Also add isFrontlightOnHW() for the emulator (it was broken)

2020-09-17 12:36 UTC, NiLuJe commented
The extremely roundabout way is unfortunately on purpose, because Kobo can't query the HW.

So, I'm afraid this doesn't quite work on Kobo, at least when some shitty corner-cases are involved (e.g., launching KOReader w/ the light off).

2020-09-17 12:54 UTC, NiLuJe commented
`BasePowerD:new` should be setting `fl_intensity` and `is_fl_on` already. Might be a chicken-egg issue on Kindle because lipc is not ready at that point?

2020-09-17 12:58 UTC, NiLuJe commented
And, checking whether the toggle updates the footer on Kobo, I just found out that while it does, the repaint is wonky as hell (it repaints on top of the existing footer? o_O).

2020-09-17 18:41 UTC, yparitcher commented
Reading the frontlight code in middle of the night does give one a headache :+1: 

my comment wasn't very clear but the issue is when going from on -> off via `turnOffFrontlight()`, `is_fl_on` is only updated after the `FrontlightStateChanged` event. this is **not** an issue on startup.

if we cant make `isFrontlightOnHW()` rely on HW (against its name), then we would have to copy the event code to `turnOffFrontlight()/turnOnFrontlight()` and also to any platform that overrides them leading to a lot of duplication. (this was already duplicated only to kobo which is why it worked there until now)

2020-09-17 19:50 UTC, NiLuJe commented
Oh, right, thanks for the clarification ;).

Unfortunately, yeah, I don't think we have a nicer solution than the duplication fest in the toggles?

2020-09-17 19:54 UTC, yparitcher commented
> Oh, right, thanks for the clarification, that makes more sense ;).
> 
> Unfortunately, yeah, I don't think we have a nicer solution than the duplication fest in the toggles?

but then we will probably have the issue of #6667 with multiple events being triggered

2020-09-17 20:22 UTC, NiLuJe commented
> but then we will probably have the issue of #6667 with multiple events being triggered :(
> unless we get rid of the event in `_setIntensity` and only have it everywhere else (much more work)

No, #6667 was pretty specifically tied to the "fancy" ramp-up/ramp-down from a different process. That's fairly specific to Kobo, unless I did it elsewhere and I forgot? ^^.

2020-09-17 21:20 UTC, yparitcher commented
@NiLuJe 
I updated it and it didn't need to much duplication. this obsoletes your fix.
works on kindle & emulator . please test on kobo (I don't think i broke it)

2020-09-17 22:24 UTC, yparitcher commented
tests pass on my end not sure why circleci failed

2020-09-17 22:33 UTC, NiLuJe commented
Will test tomorrow, but, yeah, that looks good ;).

Didn't remember that the whole `_setIntensity` weirdness came to be solely for the toggles, this definitely feels cleaner ;).

2020-09-18 11:13 UTC, NiLuJe requested changes
There's a `_setIntensity` reference left in a comment @ `frontend/device/kindle/powerd.lua`:`24`, but other than that, LGTM, and it appears to behave on Kobo ;).

Thanks!

2020-09-21 00:59 UTC, yparitcher commented
> There's a `_setIntensity` reference left in a comment @ `frontend/device/kindle/powerd.lua`:`24`, but other than that, LGTM, and it appears to behave on Kobo ;).
> 
> Thanks!

done

2020-09-21 01:05 UTC, NiLuJe approved these changes

2020-09-21 01:25 UTC, yparitcher commented
no clue why CircleCi decided to fail. otherwise I am ready to merge

2020-09-21 01:34 UTC, NiLuJe commented
Reran it for fun, but you're good to go, feel free to merge ;).

2020-09-21 01:48 UTC, merged