Add columns to ReaderZooming paged_modes
koreader/koreader pull request #6970
Opened 2020-12-09 23:40 UTC by johnbeard

This means it will warn when changing to continuous mode while
zoom to columns is active.

----

This doesn't fix #6822 but it's related to a fix since probably all members of `paged_modes` probably should also warn/autofix in reverse (i.e. when changing the zoom mode)

2020-12-10 07:08 UTC, Frenzie commented
> warn/autofix

For the majority of them, autofix. I added a couple of warnings originally because there are certain combinations that don't really make sense (e.g., zoom to page + continuous) but some people still want to use them. But zoom to fit column + continuous is completely broken. I never intended warnings for such a scenario.

2020-12-10 07:10 UTC, Frenzie requested changes

2020-12-10 07:10 UTC, Frenzie commented on frontend/apps/reader/modules/readerview.lua
> +content width or zoom to rows.
```suggestion
Continuous view (scroll mode) works best with zoom to page width, zoom to content width or zoom to rows.
```

2020-12-10 07:10 UTC, Frenzie commented on frontend/apps/reader/modules/readerview.lua
> +columns, continuous view can cause unexpected shifts when turning pages.]]),
```suggestion
In combination with zoom to fit page, page height, content height, content or columns, continuous view can cause unexpected shifts when turning pages.]]),
```

2020-12-10 10:34 UTC, johnbeard commented
@Frenzie so what to do in this case (changing from paged -> continuous)? still warn?

2020-12-10 10:48 UTC, Frenzie commented
That depends on how much time you're willing to put in. The PR is
acceptable to me for the moment as a quick interim solution, but if you
have the time to do it right of course I'd much rather see that instead.

On Thursday, December 10, 2020, John Beard <notifications@github.com> wrote:

> @Frenzie <https://github.com/Frenzie> so what to do in this case
> (changing from paged -> continuous)? still warn?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/koreader/koreader/pull/6970#issuecomment-742435107>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABRQBN2QRPQDIEK3I3NLMDSUCP5NANCNFSM4UUG4QTQ>
> .
>

2020-12-10 12:54 UTC, jperon commented
I'd plan to add the possibility, with columns and continuous mode, to add the beginning of next column to the end of current one (hope I'm clear enough…); but I won't have much time to work on it for a while, and don't really know all that's involved.

2020-12-10 12:56 UTC, Frenzie approved these changes
@johnbeard Please let me know what you plan to do. It's ready to merge, but I don't want to bother the translators with this if it won't be necessary.

2020-12-10 14:32 UTC, johnbeard commented
@Frenzie my plan was to use this commit to get the paged_modes array right and then hopefully build on it to autofix in future.

The text will stand anyway: even if there's a dialog in future ("erk, this is probably wrong, what to do: ignore and set anyway, autofix, cancel"), the warning text will be this string.

2020-12-10 14:46 UTC, Frenzie commented
Specifically this new string with the addition of rows/columns?

2020-12-11 17:42 UTC, johnbeard commented
> Specifically this new string with the addition of rows/columns?

This one:

> Continuous view (scroll mode) works best with zoom to page width, zoom to content width or zoom to rows.
> In combination with zoom to fit page, page height, content height, content or columns, continuous view can cause unexpected shifts when turning pages.

Will be the same no matter if there's an "autofix" option or not.

2020-12-11 18:28 UTC, merged

2020-12-11 18:30 UTC, Frenzie commented
I don't think I agree (i.e., why confuse users with nonsense about columns when you can't select continuous+columns at the same time in the first place), but since the strain on translators only consists of applying the diff and the string is accurate to the current situation I won't belabor the point.