Update PDF annotations when changing bookmark text
koreader/koreader pull request #7411
Opened 2021-03-14 09:59 UTC by Toromtomtom

This changes the PDF annotation contents each time the corresponding bookmark text is edited. When the annotations are written to the PDF file, the annotation contents are saved as well into the PDF.

In my initial tests it works - I can see the bookmark texts in the PDF viewer Okular. However, there are still some rough edges (partly due to my inexperience with the code base and with Lua):
- To touch as little existing code as possible, I duplicated some code. Once verified that everything works, some refactoring should be done.
- More error checking/reporting should be added.
- Tests should be added for the feature.

Depends on some [low-level additions to koreader-base](https://github.com/koreader/koreader-base/pull/1327).

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7411)

2021-03-14 10:03 UTC, Toromtomtom commented on frontend/apps/reader/modules/readerbookmark.lua
> +                item.pboxes = pboxes
We need to save the pboxes from the (highlight) item, as we need them later to identify the PDF annotation belonging to this bookmark.

2021-03-14 18:29 UTC, poire-z commented
I'm totally unfamiliar with PDF, annotations, highlight in PDF (and if these are different things) and how people use the "Save document" feature.
But I believe currently, any stuff that is to be written in the PDF gets handled at document quit time: that's where we get the prompt to write stuff into the PDF - so I guess that's also when it happens when people have disable prompt to use "always".
Was worried you would write stuff to disk on any wrong highlighy I could make, but I see that you just somehow cloned PdfDocument:saveHighlight() to do not much more than what it does :)
So, how does that work ? These 2 functions just add some stuff in memory when called (so, no I/O write to disk ?), and it's only at close time that things get flushed to disk by PdfDocument:writeDocument() ?

2021-03-14 19:50 UTC, Toromtomtom commented
> But I believe currently, any stuff that is to be written in the PDF gets handled at document quit time: that's where we get the prompt to write stuff into the PDF - so I guess that's also when it happens when people have disable prompt to use "always".
> Was worried you would write stuff to disk on any wrong highlighy I could make, but I see that you just somehow cloned PdfDocument:saveHighlight() to do not much more than what it does :)
> So, how does that work ? These 2 functions just add some stuff in memory when called (so, no I/O write to disk ?), and it's only at close time that things get flushed to disk by PdfDocument:writeDocument() ?

Yes, that seems to be the case. For example, I observed that, when I added/edited an annotation but killed the emulator before it wrote the file, the PDF file was unchanged.

The mupdf interface works on the in-memory representation of the PDF file. Interestingly, that in-memory representation also contains PDF annotations for which no highlight/bookmark in koreader exists. Those can in principle be edited as well, although that is quite confusing UI-wise. I therefore made sure that editing PDF annotations is only possible if a corresponding koreader highlight/bookmark exists.

2021-03-15 11:33 UTC, Frenzie approved these changes
I'm not really familiar with the API but it looks okay to me.

2021-03-15 12:12 UTC, Toromtomtom commented
I will try to do some further testing later today and polish this a bit. Then it will be ready for merging, I guess.

2021-03-15 17:00 UTC, Toromtomtom commented
The last commit fixed a crash when editing an annotation in a non-PDF document. From my point of view this is now ready to go.

I will try to do some refactoring and submit a new PR soon.

2021-03-19 18:17 UTC, Toromtomtom commented
Anything I can do to move this forward? It seems like this PR has already been approved, so I'm hesitant to make substantial changes now. Or shall I continue pushing changes? There is still some refactoring to be done.

2021-03-19 18:30 UTC, Frenzie commented
For me it doesn't really matter in this instance. I can merge it like this and then you can open a follow-up PR, or you could continue adding more commits to this PR.

2021-03-22 11:55 UTC, Toromtomtom commented
OK, this should now be good to go. 

I also added a function that deletes annotations from the in-memory representation of the PDF file when the corresponding highlight is removed. Before this, annotations that were added and then removed in koreader were being written to the PDF.

2021-03-22 17:35 UTC, NiLuJe requested changes
Besides the `page` mishap, looks good, thanks!

2021-03-22 17:35 UTC, NiLuJe commented on frontend/document/pdfdocument.lua
> +    end
`page` isn't `close`d here.

2021-03-22 20:07 UTC, NiLuJe approved these changes
:lgtm:

2021-03-23 09:31 UTC, merged