Gesture manager: disable assignment for hold "Plus" button
koreader/koreader pull request #7592
Opened 2021-04-24 11:51 UTC by hius07

Holding the "Plus" button is reserved for content refresh in https://github.com/koreader/koreader/pull/7559.

2021-04-24 11:58 UTC, Frenzie requested changes
That'd be a step backwards. Please assign it as the default action and leave it open for customization. ;-)

2021-04-24 12:01 UTC, hius07 commented
Should https://github.com/koreader/koreader/pull/7559 be reverted?

2021-04-24 12:06 UTC, Frenzie commented
As a part of implementing it properly, yes, but if you mean asap then I don't see why. ^_^

2021-04-24 12:13 UTC, hius07 commented
Right now in the gesture manager we can assign an action to the hold_top_right_corner, but it has no effect, doesn't work.

2021-04-24 12:25 UTC, hius07 commented
Should we also free the hold_top_left_corner for customization?
We have "Set as HOME folder" in the Plus menu and in the folder context menu.

2021-04-24 14:10 UTC, Frenzie commented
> Should we also free the hold_top_left_corner for customization?

Yes, that's all WIP/TBD.

2021-04-24 14:12 UTC, Frenzie commented
But beware, the remainders are on purpose because they're often hard, cf. https://github.com/koreader/koreader/pull/6957

I'm primarily talking about the fact that nothing new of the sort should be added.

2021-04-25 06:53 UTC, hius07 commented
https://github.com/koreader/koreader/pull/7559 reverted, action added to Dispatcher.

2021-04-25 11:08 UTC, Frenzie commented
Which migration?

2021-04-25 11:23 UTC, hius07 commented
> Which migration?

https://github.com/koreader/koreader/blob/ea6576d2b6b25baf5c5f98293fa9e5e7115ed8c7/plugins/gestures.koplugin/migration.lua#L84-L85

2021-04-26 08:49 UTC, Frenzie commented
I'm not quite following — isn't this brand new?

2021-04-26 09:38 UTC, hius07 commented
Yes, this is a brand new action, so migration isn't required, right?

2021-04-26 10:23 UTC, Frenzie commented
I shouldn't think so, pinging @NiLuJe just in case.

2021-04-26 15:29 UTC, NiLuJe commented
It wouldn't run on existing setups anyway (it's a one time migration), so, I wouldn't think so, no.

2021-04-26 19:21 UTC, yparitcher commented
No need for migration, it is only for old gesture code to plugin conversion.

2021-04-26 19:25 UTC, yparitcher commented
Was this tested? is the hold passed through to the gesture plugin? as @Frenzie mentioned see  #6957 for where this approach did not work.

2021-04-26 19:39 UTC, hius07 commented
> Was this tested?

I assgned `refresh_content` to the `hold_top_right_corner` and it works.
I assigned other actions to the `hold_top_right_corner` and it works as well.

2021-04-26 20:11 UTC, NiLuJe commented
By "it", do you mean the Gesture, or the Button? IIRC, the issue was that it broke the Button's own handler (well, not break per-se, but it's consumed earlier and stopped).

2021-04-27 00:15 UTC, yparitcher commented
> By "it", do you mean the Gesture, or the Button? IIRC, the issue was that it broke the Button's own handler (well, not break per-se, but it's consumed earlier and stopped).

The issue was that it changing the tap zone prevented the gesture as the menu/button are higher precedence than the gesture. The menu only has a tap zone not a hold zone so this PR should be good.

2021-04-27 00:20 UTC, yparitcher commented
To make this the default you should probably change:
```diff --git a/plugins/gestures.koplugin/defaults.lua b/plugins/gestures.koplugin/defaults.lua
index 7f27f34c..4fa1273d 100644
--- a/plugins/gestures.koplugin/defaults.lua
+++ b/plugins/gestures.koplugin/defaults.lua
@@ -8,7 +8,7 @@ return {
         tap_right_bottom_corner = nil,
         tap_left_bottom_corner = Device:hasFrontlight() and {toggle_frontlight = true,} or nil,
         hold_top_left_corner = nil,
-        hold_top_right_corner = nil,
+        hold_top_right_corner = {refresh_content = true,},
         hold_bottom_left_corner = nil,
         hold_bottom_right_corner = nil,
         one_finger_swipe_left_edge_down = Device:hasFrontlight() and {decrease_frontlight = 0,} or nil,
```

2021-04-27 02:54 UTC, hius07 commented
> By "it", do you mean the Gesture, or the Button?

I meant the gesture (hold). Tapping the Plus button works as well.

2021-04-27 03:14 UTC, hius07 commented
May I ask another question concerning the Dispatcher.
We have an action
https://github.com/koreader/koreader/blob/86126d042f81e566006072ce310a5493cc403fae/frontend/dispatcher.lua#L62

But we have two different onHome events:
https://github.com/koreader/koreader/blob/86126d042f81e566006072ce310a5493cc403fae/frontend/apps/reader/readerui.lua#L749-L753
https://github.com/koreader/koreader/blob/86126d042f81e566006072ce310a5493cc403fae/frontend/apps/filemanager/filemanager.lua#L1154-L1156
Is it correct? That causes that when we invoke the action named "File browser" being in the file browser, we go to the home folder, which is not an issue but unexpectable.
When we invoke the action being in reader, file browser starts in the folder with the book.

2021-04-27 14:11 UTC, yparitcher approved these changes

2021-04-27 14:35 UTC, NiLuJe commented
I mean, if you set a "Go to FM" action while *inside* the FM, you sorta expect stuff to do something else ;).

2021-04-28 04:46 UTC, hius07 commented
This PR is finished and tested. Making https://github.com/koreader/koreader/issues/7477 more flexible.

2021-05-05 18:43 UTC, merged