OPDS catalog: add book info button
koreader/koreader pull request #7767
Opened 2021-05-27 15:54 UTC by hius07

Useful before download.
Screenshots from flibusta.

![1](https://user-images.githubusercontent.com/62179190/119858069-caf55f80-bf1c-11eb-80a3-7a0d1b41b8ef.png)
--
![2](https://user-images.githubusercontent.com/62179190/119858089-ce88e680-bf1c-11eb-84fb-061dc3fd3c0b.png)

2021-05-27 16:32 UTC, NiLuJe commented
I'm mildly intrigued how you can end up with a `content` block given:

https://github.com/koreader/koreader/blob/b8d658b922404974ac5acd20a8843e665133d3c3/plugins/opds.koplugin/opdsparser.lua#L75-L78

^^

2021-05-27 16:34 UTC, NiLuJe commented
And if we don't, the first calibre book I tried:

```
./luajit: frontend/util.lua:1112: attempt to call method 'gsub' (a nil value)
stack traceback:
        frontend/util.lua:1112: in function 'htmlToPlainTextIfHtml'
        plugins/opds.koplugin/opdsbrowser.lua:678: in function 'callback'
        frontend/ui/widget/button.lua:347: in function 'handleEvent'
        frontend/ui/widget/container/inputcontainer.lua:263: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
        ...
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/uimanager.lua:1111: in function 'sendEvent'
        frontend/ui/uimanager.lua:223: in function '__default__'
        frontend/ui/uimanager.lua:1573: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1653: in function 'handleInput'
        frontend/ui/uimanager.lua:1700: in function 'run'
        ./reader.lua:323: in main chunk
        [C]: at 0x00014161
```

2021-05-27 16:47 UTC, NiLuJe commented
Reason: it's a table, not a string.

And even if you flatten it, it tends to crash in fund and interesting ways.? (Plus, potentially unsanitized HTML, brrr!).

In short: nice idea in theory, extremely problematic in practice ;).

2021-05-27 16:51 UTC, hius07 commented
Flibusta gives in opds output `<content type="text/html">`, so it remains in `item.content` and looks good.
Can this be kept in some way?

2021-05-27 16:54 UTC, Frenzie commented
Since it doesn't need a separate request, maybe you could just include a description more directly? (up to few hundred chars and/or a few lines)

2021-05-27 16:58 UTC, NiLuJe commented
That doesn't make sense: it's *never* supposed to be a string, it's a parsed tree from luxl:

```
05/27/21-18:56:00 DEBUG item.content {
    ["type"] = "xhtml",
    ["div"] = {
        ["xmlns"] = "http://www.w3.org/1999/xhtml",
        ["p"] = "Rights: Public domain in the USA.",
    },
}
```

(Which means flattening that in a meaningful way is much easier said than done anyway ^^).

2021-05-27 16:59 UTC, hius07 commented
> include a description more directly?

Excuse me, added to the first post.

Isn't it extremely cruel to kill the whole `content` for all sites just because of calibre?

2021-05-27 17:00 UTC, NiLuJe commented
It's not because of calibre, it's because of luxl ;).

It's a block that has nothing relevant in in 75% of the time (ironically, except in calibre's case), but that was responsible for 99% of the "oops, parsing failed and *silently* prevented *some* items from showing up, which is very much worse than whatever we could salvage it for ;).

2021-05-27 17:02 UTC, NiLuJe commented
TL;DR: Hard veto from myself unless we also get a working XML & HTML parser ;)

2021-05-27 17:05 UTC, Frenzie commented
@hius07 
> Excuse me, added to the first post.

I meant that if it's just 3-5 lines you could probably just show it on download (with an ellipsis for longer in combination with your popup) but that wasn't taking anything @NiLuJe said into account.

2021-05-27 17:14 UTC, NiLuJe commented
I don't rightly recall exactly how luxl(mis)behaves, so I wouldn't mind a glance at the actual code of the OPDS feed you showed in your screenshot, but, it's *possible* `<content>blah</blah>` ends up stored as a string if there are no tags inside.

In which case:

```
enabled = item.content ~= nil and type(item.content) == "string",
```

I'd *really* like to see the code of your feed to confirm first, though ;).

2021-05-27 17:29 UTC, NiLuJe commented
Mkay, `luxl` is weird, but, yeah, that works, for some reason.

2021-05-27 17:30 UTC, NiLuJe requested changes
Until something else blows up, this would be fine by me and should cover at least not horribly breaking the default list of servers.

2021-05-27 17:30 UTC, NiLuJe commented on plugins/opds.koplugin/opdsbrowser.lua
> +            enabled = item.content ~= nil,
```suggestion
            enabled = item.content ~= nil and type(item.content) == "string",
```

2021-05-27 17:49 UTC, hius07 commented on plugins/opds.koplugin/opdsbrowser.lua
> +            enabled = item.content ~= nil,
Thanks, that works with flibusta.

The output from the first post screenshot

`<content type="text/html">
    &lt;p class=book&gt;Трагедия «Гамлет» является одной из вершин творчества Шекспира. В основе пьесы лежит трагическая история датского принца Гамлета, притворившегося безумным, чтобы отомстить убийце отца, завладевшего престолом. Внутренняя душевная борьба, связанная с ужасным открытием тайны смерти отца, в сочетании с неприятием низменной среды королевского двора и желанием исправить мир приводит Гамлета к страданиям, которые становятся причиной его собственной гибели и смерти окружающих его людей.&lt;/p&gt;
   &lt;br/&gt;Перевод: Пастернак Борис Леонидович&lt;br/&gt;Год издания: 1600&lt;br/&gt;Формат: fb2&lt;br/&gt;Язык: ru&lt;br/&gt;Размер: 640 Kb&lt;br/&gt;Скачиваний: 25170&lt;br/&gt;</content>`

2021-05-27 18:12 UTC, NiLuJe commented
> Possibly because Flibusta uses html entities for `<` & `>` inside the content block :?.

Yep, that's the ticket.

Which means I can probably salvage that block in a more generic manner...

2021-05-27 18:12 UTC, NiLuJe approved these changes

2021-05-27 19:00 UTC, NiLuJe commented
Actually, posting the screenshot in #7768: shouldn't we use the book's title as the widget's title here, instead of "book description:"?

2021-05-27 19:25 UTC, hius07 commented
Much better!

2021-05-27 20:06 UTC, hius07 commented
Long title

![1](https://user-images.githubusercontent.com/62179190/119890160-28e76e80-bf40-11eb-97e4-30b29f54179f.png)

2021-05-28 02:41 UTC, NiLuJe commented
Another minor tweak, because `OPDSBrowser:genItemTableFromCatalog` already takes care of sanitizing this in case tha tuhor field is missing:

```diff
diff --git a/plugins/opds.koplugin/opdsbrowser.lua b/plugins/opds.koplugin/opdsbrowser.lua
index eae36a2ce..0bc643e0e 100644
--- a/plugins/opds.koplugin/opdsbrowser.lua
+++ b/plugins/opds.koplugin/opdsbrowser.lua
@@ -536,10 +536,7 @@ function OPDSBrowser:downloadFile(item, filetype, remote_url)
     -- Download to user selected folder or last opened folder.
     local download_dir = self.getCurrentDownloadDir()
 
-    local filename = item.title .. "." .. filetype
-    if item.author then
-        filename = item.author .. " - " .. filename
-    end
+    local filename = item.text .. "." .. filetype
 
     filename = util.getSafeFilename(filename, download_dir)
     local local_path = download_dir .. "/" .. filename
@@ -674,7 +671,7 @@ function OPDSBrowser:showDownloads(item)
             callback = function()
                 local TextViewer = require("ui/widget/textviewer")
                 UIManager:show(TextViewer:new{
-                    title = item.author .. " - " .. item.title,
+                    title = item.text,
                     text = util.htmlToPlainTextIfHtml(item.content),
                 })
             end,
```

2021-05-28 03:06 UTC, hius07 commented
When you wrote the comment, I was looking at my Kindle testing `item.text` )

2021-05-28 03:16 UTC, hius07 commented
Can we change
`enabled = item.content ~= nil and type(item.content) == "string"`
to just
`enabled = type(item.content) == "string"`?

2021-05-28 04:18 UTC, hius07 commented
> Another minor tweak

Book name in the catalog wasn't equal to the saved file name.
https://github.com/koreader/koreader/blob/b8d658b922404974ac5acd20a8843e665133d3c3/plugins/opds.koplugin/opdsbrowser.lua#L488
https://github.com/koreader/koreader/blob/b8d658b922404974ac5acd20a8843e665133d3c3/plugins/opds.koplugin/opdsbrowser.lua#L539-L541
Should we keep the difference? Title or author to be the first?

2021-05-28 05:22 UTC, NiLuJe commented
> Can we change
> `enabled = item.content ~= nil and type(item.content) == "string"`
> to just
> `enabled = type(item.content) == "string"`?

Yeah, good call (`type(nil)` returns `"nil"`).

2021-05-28 05:24 UTC, NiLuJe commented
> > Another minor tweak
> 
> Book name in the catalog wasn't equal to the saved file name.
> 
> https://github.com/koreader/koreader/blob/b8d658b922404974ac5acd20a8843e665133d3c3/plugins/opds.koplugin/opdsbrowser.lua#L488
> 
> https://github.com/koreader/koreader/blob/b8d658b922404974ac5acd20a8843e665133d3c3/plugins/opds.koplugin/opdsbrowser.lua#L539-L541
> 
> Should we keep the difference? Title or author to be the first?
> 
> As for my use case, I'd keep the difference.
> When browsing opds catalog the books by one author should be sorted by the title.
> Downloaded books by various authors might be mixed in a folder, so the filenames should begin with the author.

I hadn't really thought through the differences, just noticed 'em and thought, "oh, well, DRYer".

But, yeah, everything you said makes perfect sense, agreed!

2021-05-28 11:30 UTC, hius07 commented
Seems too much of the bold text?

![1](https://user-images.githubusercontent.com/62179190/119977425-15c8b300-bfc1-11eb-8e1c-715d094bd43c.png)
![2](https://user-images.githubusercontent.com/62179190/119977432-195c3a00-bfc1-11eb-98f4-8541e7e0e023.png)

2021-05-29 23:03 UTC, NiLuJe approved these changes

2021-05-29 23:03 UTC, NiLuJe commented on plugins/opds.koplugin/opdsbrowser.lua
> +            text = _("Book info"),
Possibly make it `Book information`, to match the hold menu in the FM?

2021-05-30 03:21 UTC, merged