Calibre plugin - Series/Tag browser updated to show back button.
koreader/koreader pull request #8869
Opened 2022-03-04 05:00 UTC by etaletovic

When browsing tags and series there was no way to go "back" from tag/series results. Figured we can enable return button navigation by pushing entry to paths property of Menu widget.

When return button is enabled it is overlapping with rounded border previously present on browse widget so I made it borderless.

2022-03-11 00:37 UTC, etaletovic commented
Found a bug. Working on fixing it.

2022-03-12 02:02 UTC, etaletovic commented
Seems to be working as I expect it. Tested using emulator and Libra H20.

2022-03-15 23:10 UTC, pazos approved these changes
Looks good. I don't have time to test it in the near future. 

LGTM and see how it behaves in "production" :D

2022-03-16 19:02 UTC, Frenzie requested changes
Could you fix these issues?
```
    plugins/calibre.koplugin/search.lua:6:7: unused variable 'CenterContainer'
    plugins/calibre.koplugin/search.lua:17:7: unused variable 'Size'
    plugins/calibre.koplugin/search.lua:384:1: line contains only whitespace
    plugins/calibre.koplugin/search.lua:459:1: line contains only whitespace
```

2022-03-16 20:16 UTC, etaletovic commented
@Frenzie Done. QQ: What do you execute to get those warnings? I was just running it with ``` ./kodev run ```

2022-03-16 20:26 UTC, etaletovic commented
I had to install luacheck but yeah I see it now. Good to know going forward.

2022-03-16 20:45 UTC, merged

2022-03-16 20:45 UTC, Frenzie commented
Thanks!