Battery statistics: schedule on full minute, avoid multiple schedulings
koreader/koreader pull request #9032
Opened 2022-04-23 20:24 UTC by zwim

Shift the first scheduling of the checkers to a full minute (rounded down to the previous minute), the consecutive schedule are multiples of minutes. This is to reduce wakeups from standby.

Fix the missing unschedule of the checkers, when the checker intervals are changed from the menu (to avoid multiple scheduled checkers).

Please merge before #8999, as there are rebase dependencies.

2022-04-23 22:59 UTC, NiLuJe commented
I'm not entirely sure I get what this change in practice, but it's Saturday night, so I'm sure it'll make more sense tomorrow ;p.

(Feels sound in theory, though, although I don't use the plugin, which probably doesn't help my mushy brain to comprehend the effects of this ;p).

2022-04-23 23:20 UTC, zwim commented
Its not urgent.

1. If the thing is running and you change the a timeout it is scheduled again and runs twice, another change of timeout and you have it running and rescheduling itself three times.
2. A scheduled taks wakes the device from standby. To minimze total wakeups, it is preferable that all not really time critical tasks are scheduled together (footer is already there on every full minute :)

2022-04-23 23:26 UTC, NiLuJe commented
Oh, the intent was to bundle it around footer updates, okay, that's much clearer, thanks ;).

2022-04-27 16:42 UTC, zwim commented
Draft now, as I want to rebase this after #8999

2022-05-05 20:33 UTC, zwim commented
Rebased now. Should work.

2022-05-07 07:07 UTC, zwim commented
Ready to merge this one?

2022-05-07 07:35 UTC, hius07 commented
What is this 1 second difference?
https://github.com/koreader/koreader/blob/de4c1749fdc6388741d8aaad90bfbf085f6548e2/frontend/apps/reader/modules/readerdevicestatus.lua#L49-L50
https://github.com/koreader/koreader/blob/de4c1749fdc6388741d8aaad90bfbf085f6548e2/frontend/apps/reader/modules/readerfooter.lua#L809

2022-05-07 08:15 UTC, zwim commented
> What is this 1 second difference?
 
Changed not, to 1 second after the full minute.

2022-05-08 18:31 UTC, NiLuJe requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9032)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hius07 and @zwim)

___
*[`frontend/apps/reader/modules/readerdevicestatus.lua` line 22 at r2](https://reviewable.io/reviews/koreader/koreader/9032#-N1ZvmeTET3nszPWhgCV:-N1ZvmeTET3nszPWhgCW:b-xzb2sw) ([raw file](https://github.com/koreader/koreader/blob/763d4219f9ba3e9e5e00ba1472c14961c3b80e46/frontend/apps/reader/modules/readerdevicestatus.lua#L22)):*
> ```Lua
>         self.battery_threshold = G_reader_settings:readSetting("device_status_battery_threshold", 20)
>         self.battery_threshold_high = G_reader_settings:readSetting("device_status_battery_threshold_high", 100)
>         -- If sync is true, schedule on a full minute (to reduce wakeups from suspend).
> ```

I would definitely mention that this is to match <whatever>'s behavior here, otherwise it's just plain confusing ;).


<!-- Sent from Reviewable.io -->

2022-05-08 18:59 UTC, hius07 commented
Maybe correct the name of the PR? It is not about the statistics.

2022-05-08 20:16 UTC, NiLuJe approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9032)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hius07)



<!-- Sent from Reviewable.io -->

2022-05-09 16:23 UTC, merged