Add warm light controller for Kindle Oasis 3 #3
koreader/koreader pull request #9054
Opened 2022-04-30 15:29 UTC by slimpdev

Work on 5.14.2

2022-04-30 17:17 UTC, NiLuJe requested changes
Looks sounds, besides that small nit ;).

2022-04-30 17:17 UTC, NiLuJe commented on frontend/device/kindle/device.lua
> +
Stray LF

2022-05-01 02:28 UTC, slimpdev commented on frontend/device/kindle/device.lua
> +
oops

2022-05-01 15:12 UTC, NiLuJe approved these changes

2022-05-01 16:38 UTC, merged