Kobo: Enable power/sleep button support for Nia
koreader/koreader pull request #9591
Opened 2022-10-04 09:16 UTC by 3to8-decoder

see my bug-report/issue: https://github.com/koreader/koreader/issues/9590

2022-10-04 12:47 UTC, Frenzie approved these changes
If it works. ;-)

2022-10-04 16:25 UTC, NiLuJe commented on frontend/device/kobo/device.lua
> +    power_dev = "/dev/input/event2",
Nope, potentially too brittle ;).

Check if it works with `automagic_sysfs = true,` (like the Libra 2) instead.

And if it doesn't, get me the output of `ls -lash /dev/input/by-path` ;).

2022-10-04 16:26 UTC, NiLuJe requested changes
See above comment (where I pressed the wrong button :x).

I also wouldn't mind the output of

`ntx_hwconfig -l -s /dev/mmcblk0 2>/dev/null`

2023-02-02 20:12 UTC, NiLuJe commented
Still waiting on the requested data :).

2023-04-23 17:46 UTC, NiLuJe commented
Confirmed via other reports that it's a BD71828 PMIC, much like the other newer hardware revisions in that lineup, so I basically just need to output from `ls -lash /dev/input/by-path` to implement this properly ;).

2023-05-31 06:35 UTC, themaz commented
@NiLuJe here is the output:

```
[root@kobo ~]# ls -lash /dev/input/by-path
total 0
     0 drwxr-xr-x    2 root     root          80 May 31 08:31 .
     0 drwxr-xr-x    3 root     root         160 May 31 08:31 ..
     0 lrwxrwxrwx    1 root     root           9 May 31 08:31 platform-bd71828-pwrkey-event -> ../event2
     0 lrwxrwxrwx    1 root     root           9 May 31 08:31 platform-ntx_event0-event -> ../event0
[root@kobo ~]#
```

Also, the `automagic_sysfs = true` worked for me.

2023-05-31 19:21 UTC, NiLuJe commented
Superseded by #10520 (thanks for reviving this, @themaz !)

2023-05-31 19:21 UTC, closed without merging