KeyValuePage: Don't compare potential nil with number
koreader/koreader pull request #9705
Opened 2022-10-28 22:08 UTC by roygbyte

When creating a KeyValuePage with an empty table of kv_pairs, it will throw an error. 

`./luajit: frontend/ui/widget/keyvaluepage.lua:601: attempt to compare nil with number`

2022-10-28 22:58 UTC, NiLuJe commented
I'm mildly curious why you'd want to do that in the first place, and almost convinced it'll blow up later on in a whole lot of places ;).

2022-10-28 23:11 UTC, roygbyte commented
It's got to do with Gazette/Newsdownloader. When visiting the list of subscriptions, and none are created, the plugin displays an empty list with a button to add a subscription (PR pending #9495). It's not ideal. Ideal would be directing user to an altogether separate view. But that's just not what I've got to offer right now :)

2022-10-28 23:13 UTC, hius07 commented
I agree that KVP should not crash when called with `kv_pairs == nil`.
(The Menu widget shows "No items" in this case)
https://github.com/koreader/koreader/blob/d7c63edca66203dfc459f32f7a2066bee2e679e8/frontend/ui/widget/menu.lua#L577
But this should be arranged earlier, not only for key/value widths.

2022-10-28 23:22 UTC, NiLuJe commented
I was thinking of `{}`, not `nil`. Which is it? ;o).

2022-10-28 23:32 UTC, roygbyte commented
From what I can tell, it's commit https://github.com/koreader/koreader/pull/9672 that introduced the bug.

2022-10-29 02:20 UTC, weijiuqiao commented
For me, it crashes here in `KeyValuePage:init()`:
https://github.com/koreader/koreader/blob/d7c63edca66203dfc459f32f7a2066bee2e679e8/frontend/ui/widget/keyvaluepage.lua#L477
`attempt to get length of field 'kv_pairs' (a nil value)`

2022-10-29 02:44 UTC, hius07 commented
We need something similar
https://github.com/koreader/koreader/blob/d7c63edca66203dfc459f32f7a2066bee2e679e8/frontend/ui/widget/menu.lua#L641-L643
and decide what to display when kv_pairs is empty.
Menu shows "No items" in the bottom of the screen.
Titlebar buttons are available.

2022-10-29 04:27 UTC, Frenzie requested changes
Nope, assign {} somewhere please.

2022-10-29 04:27 UTC, Frenzie commented
Oh, like @hius07 already said, apologies.

2022-10-29 12:28 UTC, roygbyte commented
Just to be clear, the issue I'm reporting isn't caused by kv_pairs being nil. (Although it sounds like that's also cause for an issue.) The issue comes from this code here:

https://github.com/koreader/koreader/blob/d7c63edca66203dfc459f32f7a2066bee2e679e8/frontend/ui/widget/keyvaluepage.lua#L572-L599

Which instantiates a table called `key_widths` and `value_widths`... inserts values into those tables for every `self.items_per_page`... and then computes a width ratio if some conditions are true.

2022-10-29 12:41 UTC, hius07 commented
Great, so it would be enough to add `self.kv_pairs = self.kv_pairs or {}` to the init.

2022-10-29 12:58 UTC, hius07 commented
Agree, additional checks of `key_widths` and `value_widths` are needed.

2022-10-29 13:03 UTC, hius07 commented
Side question: which way of finding max value of an array is more effective:
-sort the array and take the last value (currently in KVP), or
-math.max(unpack(array))
?

2022-10-29 13:38 UTC, weijiuqiao commented
>The bug is caused by #key_widths being 0 (or nil?) when there are no items_per_page. Hence the nil/number comparison error.

Lgtm and good catch!

>Side question: which way of finding max value of an array is more effective:

Not sure. But here sorting makes more sense cause the order of items will be needed (to be compared one by one till a certain criterion is met)

2022-10-29 20:45 UTC, roygbyte commented
Do I need to do anything else to this PR?

2022-10-29 20:58 UTC, NiLuJe commented
https://github.com/koreader/koreader/pull/9705#issuecomment-1295697421 & https://github.com/koreader/koreader/pull/9705#issuecomment-1295829490

(a.k.a., "Trust @hius07" ;)).

2022-10-29 21:08 UTC, NiLuJe commented
I'll leave final word to @hius07, but this looks good ;).

2022-10-29 21:42 UTC, hius07 commented
Thank you, it should be fine.

2022-10-30 00:04 UTC, NiLuJe approved these changes

2022-10-30 00:05 UTC, merged